# Generated by Django 5.2.7 on 2025-10-17 04:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Story',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='The Sayings of the High One')),
                ('full_text', models.TextField(verbose_name='Cattle die, kinsmen die, you yourself must also die; but the renown never dies of anyone who gets a good one.\nCattle die, kinsmen die, you yourself must also die; I know one thing that never dies: the judgment on each dead person.')),
            ],
        ),
        migrations.CreateModel(
            name='Word',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('maori_word', models.CharField(max_length=100, verbose_name='Deyr')),
                ('english_translation', models.CharField(max_length=100, verbose_name='Cattle')),
                ('story', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='words', to='stories.story', verbose_name='The Sayings of the High One')),
            ],
        ),
    ]
