# Generated by Django 5.2.7 on 2025-10-22 21:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="BackgroundMusic",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        help_text="BGM Title", max_length=200, verbose_name="BGM Title"
                    ),
                ),
                (
                    "audio_file",
                    models.FileField(
                        upload_to="bgm/", verbose_name="BGM audio file (.m4a)"
                    ),
                ),
            ],
            options={
                "verbose_name": "Background Music",
                "verbose_name_plural": "Background Music Library",
            },
        ),
        migrations.RemoveField(
            model_name="story",
            name="full_text",
        ),
        migrations.RemoveField(
            model_name="word",
            name="story",
        ),
        migrations.AddField(
            model_name="word",
            name="english_audio",
            field=models.FileField(
                blank=True,
                null=True,
                upload_to="word_audio_english/",
                verbose_name="English Audio",
            ),
        ),
        migrations.AddField(
            model_name="word",
            name="image",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to="word_images/",
                verbose_name="Word Image",
            ),
        ),
        migrations.AddField(
            model_name="word",
            name="maori_audio",
            field=models.FileField(
                blank=True,
                null=True,
                upload_to="word_audio_maori/",
                verbose_name="Maori Audio",
            ),
        ),
        migrations.AddField(
            model_name="word",
            name="placeholder",
            field=models.CharField(
                blank=True,
                max_length=50,
                null=True,
                unique=True,
                verbose_name="Placeholder in Text (e.g., __BLANK_1__)",
            ),
        ),
        migrations.AddField(
            model_name="story",
            name="background_music",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="core.backgroundmusic",
                verbose_name="Background Music",
            ),
        ),
        migrations.CreateModel(
            name="Paragraph",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "order",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Paragraph Order"
                    ),
                ),
                ("text", models.TextField(verbose_name="Paragraph Text")),
                (
                    "audio",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to="paragraph_audio/",
                        verbose_name="Paragraph Audio",
                    ),
                ),
                (
                    "story",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="paragraphs",
                        to="core.story",
                        verbose_name="Belonging Story",
                    ),
                ),
            ],
            options={
                "ordering": ["order"],
            },
        ),
        migrations.AddField(
            model_name="word",
            name="paragraph",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="words",
                to="core.paragraph",
                verbose_name="Belonging Paragraph",
            ),
        ),
    ]
