# Generated by Django 5.2.7 on 2025-10-22 23:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_backgroundmusic_remove_story_full_text_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="word",
            options={
                "verbose_name": "Word (in Bank)",
                "verbose_name_plural": "Word Bank",
            },
        ),
        migrations.RemoveField(
            model_name="word",
            name="paragraph",
        ),
        migrations.RemoveField(
            model_name="word",
            name="placeholder",
        ),
        migrations.AlterField(
            model_name="backgroundmusic",
            name="audio_file",
            field=models.FileField(upload_to="bgm/", verbose_name="BGM file (.m4a)"),
        ),
        migrations.AlterField(
            model_name="backgroundmusic",
            name="title",
            field=models.CharField(
                help_text="Name of a BGM", max_length=200, verbose_name="BGM Title"
            ),
        ),
        migrations.AlterField(
            model_name="word",
            name="maori_word",
            field=models.CharField(
                max_length=100, unique=True, verbose_name="Maori word"
            ),
        ),
        migrations.CreateModel(
            name="BlankLink",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "placeholder",
                    models.CharField(
                        max_length=50,
                        verbose_name="Placeholder in Text (e.g., __BLANK_water__)",
                    ),
                ),
                (
                    "paragraph",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="blank_links",
                        to="core.paragraph",
                        verbose_name="Paragraph",
                    ),
                ),
                (
                    "word",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="core.word",
                        verbose_name="Linked Word from Bank",
                    ),
                ),
            ],
            options={
                "verbose_name": "Blank Link",
                "verbose_name_plural": "Blank Links",
                "unique_together": {("paragraph", "placeholder")},
            },
        ),
    ]
