# Generated by Django 5.2.7 on 2025-10-23 01:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0003_alter_word_options_remove_word_paragraph_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="story",
            name="word_bank",
            field=models.ManyToManyField(
                blank=True,
                related_name="stories",
                to="core.word",
                verbose_name="Select Words for this Story's Bank",
            ),
        ),
    ]
