# Generated by Django 5.2.7 on 2025-10-27 04:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0004_story_word_bank"),
    ]

    operations = [
        migrations.AddField(
            model_name="story",
            name="picture",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to="story_pictures/",
                verbose_name="Story Picture",
            ),
        ),
    ]
