# Generated by Django 5.2.7 on 2025-10-27 05:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0005_story_picture"),
    ]

    operations = [
        migrations.CreateModel(
            name="StoryPicture",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        help_text="A recognizable name for this picture",
                        max_length=200,
                        verbose_name="Picture Title",
                    ),
                ),
                (
                    "image_file",
                    models.ImageField(
                        upload_to="story_pictures/", verbose_name="Picture file"
                    ),
                ),
            ],
            options={
                "verbose_name": "Story Picture",
                "verbose_name_plural": "Story Picture Library",
            },
        ),
        migrations.RemoveField(
            model_name="story",
            name="picture",
        ),
        migrations.AddField(
            model_name="story",
            name="story_picture",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="core.storypicture",
                verbose_name="Story Picture",
            ),
        ),
    ]
