# Generated by Django 5.2.7 on 2026-03-07 23:16

import core.models
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0006_storypicture_remove_story_picture_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="AppConfig",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "key",
                    models.CharField(
                        help_text="Unique identifier for this configuration setting",
                        max_length=100,
                        unique=True,
                        verbose_name="Configuration Key",
                    ),
                ),
                (
                    "value",
                    models.TextField(
                        help_text="The value for this configuration setting",
                        verbose_name="Configuration Value",
                    ),
                ),
                (
                    "description",
                    models.CharField(
                        blank=True,
                        help_text="Human-readable description of this setting",
                        max_length=255,
                        verbose_name="Description",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Last Updated"),
                ),
            ],
            options={
                "verbose_name": "Application Configuration",
                "verbose_name_plural": "Application Configurations",
            },
        ),
        migrations.AlterField(
            model_name="backgroundmusic",
            name="audio_file",
            field=models.FileField(
                upload_to="bgm/",
                validators=[
                    django.core.validators.FileExtensionValidator(
                        ["mp3", "m4a", "aac", "wav", "ogg"]
                    ),
                    core.models.validate_audio_file_size,
                ],
                verbose_name="BGM file (.m4a, .mp3)",
            ),
        ),
        migrations.AlterField(
            model_name="paragraph",
            name="audio",
            field=models.FileField(
                blank=True,
                null=True,
                upload_to="paragraph_audio/",
                validators=[
                    django.core.validators.FileExtensionValidator(
                        ["mp3", "m4a", "aac", "wav", "ogg"]
                    ),
                    core.models.validate_audio_file_size,
                ],
                verbose_name="Paragraph Audio",
            ),
        ),
        migrations.AlterField(
            model_name="storypicture",
            name="image_file",
            field=models.ImageField(
                upload_to="story_pictures/",
                validators=[
                    django.core.validators.FileExtensionValidator(
                        ["jpg", "jpeg", "png", "webp"]
                    ),
                    core.models.validate_image_file_size,
                ],
                verbose_name="Picture file",
            ),
        ),
        migrations.AlterField(
            model_name="word",
            name="english_audio",
            field=models.FileField(
                blank=True,
                null=True,
                upload_to="word_audio_english/",
                validators=[
                    django.core.validators.FileExtensionValidator(
                        ["mp3", "m4a", "aac", "wav", "ogg"]
                    ),
                    core.models.validate_audio_file_size,
                ],
                verbose_name="English Audio",
            ),
        ),
        migrations.AlterField(
            model_name="word",
            name="image",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to="word_images/",
                validators=[
                    django.core.validators.FileExtensionValidator(
                        ["jpg", "jpeg", "png", "webp"]
                    ),
                    core.models.validate_image_file_size,
                ],
                verbose_name="Word Image",
            ),
        ),
        migrations.AlterField(
            model_name="word",
            name="maori_audio",
            field=models.FileField(
                blank=True,
                null=True,
                upload_to="word_audio_maori/",
                validators=[
                    django.core.validators.FileExtensionValidator(
                        ["mp3", "m4a", "aac", "wav", "ogg"]
                    ),
                    core.models.validate_audio_file_size,
                ],
                verbose_name="Maori Audio",
            ),
        ),
    ]
