# Generated by Django 5.2.12 on 2026-04-28 00:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0007_appconfig_alter_backgroundmusic_audio_file_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="appconfig",
            options={
                "verbose_name": "Application Configuration",
                "verbose_name_plural": "Application Configuration",
            },
        ),
        migrations.RemoveField(
            model_name="appconfig",
            name="description",
        ),
        migrations.RemoveField(
            model_name="appconfig",
            name="key",
        ),
        migrations.RemoveField(
            model_name="appconfig",
            name="value",
        ),
        migrations.AddField(
            model_name="appconfig",
            name="menu_bgm",
            field=models.ForeignKey(
                blank=True,
                help_text="Select background music for the main menu",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="core.backgroundmusic",
                verbose_name="Menu Background Music",
            ),
        ),
    ]
